### ISSUE TITLE
Retrieving Coregistration from CoregistrationUI

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10227]
#### Describe the new feature or enhancement
I need to programmatically retrieve the coregistration results from `CoregistrationUI` after the user has finished coregistration, without requiring them to explicitly save `trans` and `fiducials` to disk.

Currently, there's no public API to do so: the `Coregistration` instance is stored in the private `CoregistrationUI._coreg` – which is overwritten with `None` when the `CoregistrationUI` window is closed.

#### Describe your proposed implementation
`CoregistrationUI._coreg` should become public as `CoregistrationUI.coreg` or `CoregistrationUI.coregistration`, and `CoregistrationUI._clean()` should not overwrite the `Coregistration` instance on window close.

#### Describe possible alternatives
`mne.gui.coregistration()` could return the `Coregistration` instance after `CoregistrationUI` has been closed, instead of returning `CoregistrationUI`. But I believe this would break some workflows. Or wouldn't even be possible in non-blocking mode…

cc @GuillaumeFavelier @larsoner

**Comment by agramfort** [comment]
I would add a public method to CoregistrationUI

**Comment by hoechenberger** [comment]
> I would add a public method to CoregistrationUI

This could be another option, yes. Something that returns a tuple: a dict with fiducials (name->coords), and the head->mri Transform

**Comment by GuillaumeFavelier** [comment]
Why not using `Coregistration` in the first place? It is public and we added it for this purpose in the first place (I mean scripting coregistration).

My work on coregistration started in https://github.com/mne-tools/mne-python/pull/9516 because `jhouck` wanted to [programmatically use the coreg UI](https://github.com/mne-tools/mne-python/pull/6693/files).

I would prefer that we improve/refactor `Coregistration` if it lacks features. And on the topic of trans, it actually has a [`trans` property](https://github.com/mne-tools/mne-python/blob/main/mne/coreg.py#L1951-L1954) which does not save to disk.

**Comment by hoechenberger** [comment]
> Why not using `Coregistration` in the first place?

My use case is that we perform an interactive coregistration via `mne.gui.coregistration()`, and after that's done, I want to write the results (transformation and fiducials) to BIDS. To make this work reliably, I'd like to be able to directly extract this information from the `CoregistrationUI` object somehow, without forcing the user to create files first – whose filenames I cannot control.

Does that make sense?

**Comment by GuillaumeFavelier** [comment]
> Does that make sense?

If `CoregistrationUI` must be used then indeed, at the moment, there is no public way to do that, I understand :ok_hand:

**Comment by hoechenberger** [comment]
I can give this a shot if you don't mind

**Comment by GuillaumeFavelier** [comment]
You're more than welcome to do so @hoechenberger
