### ISSUE TITLE
BUG: Notebook server produces blank images by default

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#10391]
@GuillaumeFavelier see https://mne.discourse.group/t/support-for-3d-brain-visualization-in-headless-mode/4375/12

I wonder if we should try to be smart about `ANTIALIAS` and set it to False under some circumstances. Maybe we can detect a MESA renderer? Or maybe we just always set it to False for the notebook backend? WDYT?

**Comment by GuillaumeFavelier** [comment]
>  Maybe we can detect a MESA renderer?

I prefer this idea because AFAIK we encounter this issue mostly when using MESA. Plus it should be simple enough to do using `pyvista.GPUInfo` (and I think the issue with the report crashing should be solved for the next release).

> Or maybe we just always set it to False for the notebook backend? 

It might be too much. I often use the `notebook` 3d backend locally for testing so I would have to enable it explicitly. Let's keep it as a backup plan if relying on MESA is not reliable.
