### ISSUE TITLE
Add Standardized Measurement Error for ERP analysis

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#10647]
In a recent paper, Steven Luck et al. have proposed a new data quality measure called the [Standardized Measurement Error](https://onlinelibrary.wiley.com/doi/full/10.1111/psyp.13793). They suggest that publications should report this measure because it facilitates comparisons of data quality across different studies.

I think it would be great if MNE-Python included this measure. Currently, I don't have time to implement it myself, but I wanted to start a discussion whether or not you think this could be a valuable addition (and if so, how it could be best integrated into the current ERP analysis tools).

**Comment by larsoner** [comment]
From a quick look at the abstract, sounds reasonable to me. Happy to review if someone implements this!

As far as an API goes, I guess we could have a high-level function that operates on `epochs` probably (and assume you've already subselected one condition), and a low-level one that operates on an array of shape `(n_epochs, ...)` (not sure what `...` would be yet) so that it could be applied to single-trial source label time course waveforms as well for example.
