### ISSUE TITLE
Tutorial thumbnail popovers should be removed

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10724]
The popover texts seem to be based on the raw ("un-processed") input, so for the devel docs I get e.g.:

![Screen Shot 2022-06-08 at 22 15 52](https://user-images.githubusercontent.com/2046265/172710328-83c19467-5279-4f26-be88-378467b13e93.png)

And for the stable docs the CSS seems to be broken:

![Screen Shot 2022-06-08 at 22 16 05](https://user-images.githubusercontent.com/2046265/172710403-91ebd965-3bf7-4afb-8313-e900f1db9f36.png)

Besides, for those tutorials where I don't see such layouting issues, the provided information is not helpful to me at all as it's just too little text. If we want more info, we should amend the captions of the thumbnails.

Besides, I don't like stuff jumping all around on my screen as I move the mouse cursor over it anyway, it's irritating; and it hides content.

So my vote is clear – let's get rid of those popovers entirely, and potentially amend the captions.

@drammock WDYT?

**Comment by drammock** [comment]
The content for those is drawn from the first sentence of the tutorial text. I agree it is of limited use. At some point @larsoner had done some magic in sphinx-gallery to make it "sanitize" those preview snippets so that backticks and tildes would not render, but it looks like it's not working in all cases anymore.  I have no objection to suppressing them. Can you see if there's a config option for sphinx-gallery that will just turn them off?

**Comment by larsoner** [comment]
We can just set display none in the CSS for the class. It's easier than adding yet another option to SG

**Comment by hoechenberger** [comment]
Sounds good to me!!
