### ISSUE TITLE
[ENH] Add video tutorial for coregistration

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#10801]
Before uploading this to YouTube and opening a PR to embed it in a tutorial, I wanted to ask for feedback since I didn't write the GUI, I'm just trying to make the documentation better.

https://user-images.githubusercontent.com/13473576/174907103-da5cd3d2-7f99-4815-b3b3-c28728834737.mp4

Does that look okay? Anything should be changed? cc @hoechenberger @larsoner

**Comment by cbrnr** [comment]
I think this is a great tutorial! I would show the command that launches the GUI (instead of just saying that it's in the sample file). And maybe at the end you could briefly mention that there's also a fully automated coregistration available as an alternative (https://github.com/mne-tools/mne-python/blob/main/tutorials/forward/25_automated_coreg.py)?

**Comment by alexrockhill** [comment]
I'm going to go ahead and upload to YouTube, we can always release new versions of the video, it's just nice to start somewhere. Really loving the video sphinx docs for this GUI stuff.
