### ISSUE TITLE
More resources on CircleCI

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10909]
The freely hosted Docker runners can now request more resources on CircleCI (4 CPUs & 8 GB of RAM) via
```
    resource_class: large
```
See https://circleci.com/docs/2.0/configuration-reference/#resourceclass

I already tried it in another repo and it seems to be working.

This could allow us to
- render some of the currently excluded examples/tutorials,
- parallelize more inside tutorials (`n_jobs=X`),
- use more complex (and more "natural" instead of synthetic??) data in tutorials

cc @drammock @larsoner @sappelhoff @agramfort

**Comment by hoechenberger** [comment]
See it in action here:
https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3008/workflows/0a7c98e6-40d9-4e3a-a0f4-43107719fbb0/jobs/29102/resources

**Comment by larsoner** [comment]
Are you sure they charged their OSS policy? This might be possible for mne-tools because we actually pay for the service nowadays, rather than being due to an OSS policy change at their end...

I agree we can change it if it helps with some examples, but we should really try to continue to keep example execution time and memory usage as low as possible. In this sense, our current resource class limit has actually served a useful purpose, preventing us from being lazy/wasteful sometimes. So if we do increase the resource class, we'll need to be more vigilant/conscious and do more manual checking of example resource use and code efficiency.

**Comment by hoechenberger** [comment]
> This might be possible for mne-tools because we actually pay for the service nowadays, rather than being due to an OSS policy change at their end...


Oh. Well. That's the most likely explanation then 😅
