### ISSUE TITLE
raw.plot_psd hangs in jupyter notebook

### ISSUE THREAD

**Issue by hernandezurbina** [mne-tools/mne-python#11021]
#### Describe the bug
Running plot_psd on raw data inside a jupyter notebook shows the plot but the cell hangs as if computing something even after the plot has been closed.

#### Steps to reproduce
I loaded EEG raw data in .set format. Cropped to 100s. Filtered the data using l_freq=0.1 and h_freq=40. Chose 3 channels using pick+channels, and then ran plot_psd. MNE shows the plot but the cell hangs indefinitely. I am using matplotlib with the Qt5Agg backend.

The cell in jupyter returns the following while hanging:
`[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished`

#### Expected results
Cell in jupyter finishes running.

#### Actual results
Cell hangs.

**Comment by larsoner** [comment]
@hernandezurbina can you check https://mne.discourse.group for similar issues and post there if you don't find one? It's likely this is a matplotlib<->notebook or usage problem rather than an MNE-Python one, so I'll close (unless we figure out in forum conversations this happens only for MNE plots for example)
