### ISSUE TITLE
Scaling is off for tiny_bids

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11113]
### Description of the problem

I think this screenshot demonstrates the issue:
<img width="1050" alt="Screen Shot 2022-08-29 at 16 22 03" src="https://user-images.githubusercontent.com/2046265/187223852-852b8fcd-f73f-4ba7-a9fb-35fd8007995d.png">

### Steps to reproduce

```python
# %%
from pathlib import Path
import mne_bids
from mne_bids import BIDSPath, read_raw_bids

mne_bids_root = Path(mne_bids.__file__).parents[1]
tiny_bids_root = mne_bids_root / "mne_bids" / "tests" / "data" / "tiny_bids"


bids_path = BIDSPath(
    subject='01', session='eeg', task='rest', datatype='eeg',
    root=tiny_bids_root
)
raw = read_raw_bids(bids_path)
raw.plot(block=True)
```

This is with MNE and MNE-BIDS `main`

### Expected results

Signal PTP should be in the range of maybe 300 or 500 µV max?

### Actual results

PTP amplitude is much larger (2–3 units of magnitude)

**Comment by sappelhoff** [comment]
This was added to the testing data here: https://github.com/mne-tools/mne-testing-data/pull/49

As far as I remember I recorded this data in the lab at my institute and truncated it. No idea why the scaling is off 🤔

**Comment by hoechenberger** [comment]
> No idea why the scaling is off 🤔

Could you try to read the data with BV Analyzer? I suspect our reader is the problem here…

**Comment by sappelhoff** [comment]
@alisenz -- do you have time to:

1. download the BrainVision data in question (called `bv_dig_test`, see: https://github.com/mne-tools/mne-testing-data/tree/master/montage)
2. Go to our lab and check
    3. whether you can read that data with BrainVision Analyzer
    4. It's installed on the recording PC
    5. The dongle is in the materials room (small red USB stick, should be on top right of shelf in a porcelain bowl)
6. Report here whether you:
    7. can read and plot/view the data
    8. the units "seem right", i.e., that the voltages are in a reasonable range, unlike what Richard reports above when reading the data with MNE-Python
    
? 

No worries if you don't find the time.

**Comment by alisenz** [comment]
@hoechenberger @sappelhoff the data is readable but if you expect the amplitude of 300-500 µV, this is **NOT** the case. I'm seeing min 5000 µV here:

![Capture](https://user-images.githubusercontent.com/36814874/188845564-f6231b27-03db-49d3-b118-aebb85498375.PNG)

**Comment by sappelhoff** [comment]
wow, what the hell did I do back then? At least this confirms that the issue is with the data and not with our readers. Perhaps I did some weird scaling in a misguided attempt to obscure/anonymize the data, because I thought the severe cropping wasn't enough? After all this was originally only intended for a check of montages and the Brain Products CapTrak system.

Thanks for checking @alisenz

**Comment by hoechenberger** [comment]
If we're off by 3 orders of magnitude it's probably nV instead of uV?

**Comment by sappelhoff** [comment]
I don't think so. Knowing myself from 3 years ago I think this is most likely what happened (~80% sure):

> Perhaps I did some weird scaling in a misguided attempt to obscure/anonymize the data, because I thought the severe cropping wasn't enough?

fixing this would involve:

- re-writing the `.eeg` file with sensible data (leaving vhdr and vmrk intact), e.g., using [pybv](https://github.com/bids-standard/pybv)
- updating the accompanying fif file: [`bv_dig_raw.fif`](https://github.com/mne-tools/mne-testing-data/blob/master/montage/bv_dig_raw.fif)
- tiny_bids dataset in mne-bids needs to be re-written
- mne-tests don't need to be updated, because only the locs are being checked: https://github.com/mne-tools/mne-python/blob/9e67f7ce9100bbac452b990541e8f36a072f098a/mne/channels/tests/test_montage.py#L1021-L1028

**Comment by hoechenberger** [comment]
Thank you @sappelhoff for fixing this!
