### ISSUE TITLE
BUG: spatial_colors PR broke an example

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#11149]
Presumably from https://github.com/mne-tools/mne-python/pull/11017

https://app.circleci.com/pipelines/github/mne-tools/mne-python/16268/workflows/e0fbe025-9f20-4f69-ad23-3f158beb9860/jobs/48907

@drammock @hoechenberger it looks like you reviewed, could one of you have a look for a quick fix today? If not, I can do it.

**Comment by agramfort** [comment]
the problem is the following. If you do evoked.plot() it plots all channel types but if one channel types has no locations (eg EOG in the example) then spatial_colors is set to True but you get the warning when picks contains EOG.

I would suggest then to revert the commit for now unless @drammock has time to fix very quickly.
