### ISSUE TITLE
"stable" docs show docs for MNE 1.2, not the latest 1.3

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11386]
### Proposed documentation enhancement

https://mne.tools/stable/index.html

<img width="368" alt="Screenshot 2022-12-24 at 10 36 41" src="https://user-images.githubusercontent.com/2046265/209430066-231f2ee0-2c68-4b80-9148-0a463de314ef.png">

**Comment by larsoner** [comment]
FYI the release is still in progress -- I just pushed a commit to `maint/1.3` with `git commit --allow-empty -m 'CI: Deploy [circle deploy] [skip azp] [skip actions] [skip cirrus]'` but then immediately cancelled the circle run because I realized we need to do this after https://github.com/mne-tools/mne-python/pull/11387 is merged and backported.

**Comment by drammock** [comment]
closed by f2f7ddea1

**Comment by hoechenberger** [comment]
thanks!
