### ISSUE TITLE
ENH/IO: add support for EGI Netstation EEG data.

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1210]
We're currently using EGI EEG together with Neuromag data. 
I'd like to merge the EGI data into a fiff file.
I haven't explored the existing solutions for reading EGI data.
Here's what needs to be done.
- define free fiff codes
- make a decision regarding reading the `.raw` files VS matlab files
- maybe first do a BaseRaw ...

cc @agramfort

**Comment by jona-sassenhagen** [comment]
@Mensen did you get around to releasing MATLAB (or other) code to read in MFF files somewhere? I have a bunch of MFF files here I'd like to read into MNE.

**Comment by Mensen** [comment]
@jona-sassenhagen I gavemy code to read MFF files into Matlab to the guy working directly with MNE a while ago. Not sure what happened in the end. The repo I have is still in a private organisation for the department but if the code to use MFF in matlab is useful I can pass it to you directly.

**Comment by agramfort** [comment]
please share the code.

if the code is compatible with the BSD license of MNE you might get some help :)

**Comment by dengemann** [comment]
Yaeah I am that guy. I still have the code but we never did something with it as there was no urgency for our team. I am basically offline these days, if you need extended input or more see you next year folks!

**Comment by Mensen** [comment]
@dengemann Didn't mean "the guy" to sound so harsh ;)

Most of the time I just save the EEG files as .raw from EGI since those are simple binary files that are easy to load. I understand some of the advantages of MFF, but given the current headache they are to convert, they are overall a bigger problem than solution.

**Comment by jona-sassenhagen** [comment]
FWIW we have advanced EEGLAB support now, so you can export the MFF files to EEGLAB .set format (with Dr. Chennu's plugin) and import that into MNE.

**Comment by Mensen** [comment]
@jona-sassenhagen That's really helpful to know. Do you know if you can export back to EEGLAB format? I have a bunch of more advanced analysis scripts that run in Matlab and if I could just do the preprocessing in MNE and continue my analysis with Matlab I would probably be more inclined to use for every day analysis of my data.

This should probably be a different thread at this point, but since I have it hijacked, how well does Python + MNE handle huge EEG files from all night sleep recordings? The raw files are 6-12GB depending on how long people have slept. In Matlab I find to pre-process this sort of data I need at least 3x the RAM since it copies the data within a subfunction, and has to hold the original, the copy, and the preprocessed version (e,g, filtered), all in memory at the same time.

**Comment by jasmainak** [comment]
In Python, you can load data on-demand. Take a look at our option called preload: http://martinos.org/mne/stable/manual/memory.html. It might be helpful for some (but not all) processing steps ...

**Comment by Eric89GXL** [comment]
You currently have to have the data in memory to do filtering, though. But it shouldn't cause a 3x memory jump. We do hold the data in float64 (double) format, though, so if it's natively single (32 bit) then there will be a 2x memory requirement.

**Comment by ramonapariciog** [comment]
Hello!, I will put this here
https://github.com/ramonapariciog/mne-mff-reader
@dengemann @deep-introspection @SherazKhan

**Comment by Eric89GXL** [comment]
Reopening. There has also been discussion in #1687 about this. It's also related to #3953.

@ramonapariciog please open a PR if you have time. If you get stuck we can help you with comments or PRs into your branch. If you don't think you'll have time, let me know and I can try adapting your code.

**Comment by ramonapariciog** [comment]
Sorry @dengemann & @Eric89GXL, i will open it, I have the time, just give me this saturday that comes to do it.
Greetings.

**Comment by Eric89GXL** [comment]
ping @ramonapariciog. Will you have time for this anytime soon?

**Comment by agramfort** [comment]
this is done now
