### ISSUE TITLE
Collapsed Info HTML repr leads to degraded UX

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12131]
### Description of the problem

Info HTML reprs are now collapsed by default. That means that whenever I want to view Info inside e.g. a Jupyter Notebook or VS Code Python's Interactive Window, I need to click to uncollapse things. It's disrupting my workflow and I had to resort to typing `print(info)`, but this doesn't show the nice HTML representation. I'm unhappy.

### Steps to reproduce

```Python
# %%
import mne

sample_dir = mne.datasets.sample.data_path()
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

info = mne.io.read_info(sample_fname)
info
```

### Expected results

<img width="505" alt="Screenshot 2023-10-24 at 17 19 28" src="https://github.com/mne-tools/mne-python/assets/2046265/4498478c-9238-4662-a2fb-a9c47003f32e">

### Actual results

<img width="506" alt="Screenshot 2023-10-24 at 17 19 46" src="https://github.com/mne-tools/mne-python/assets/2046265/e173cbf7-a3c1-4c27-9032-58061456b507">

### Additional information

At least the `General` and `Channel` sections should be uncollapsed by default

Filing as a bug because I really dislike it and it disrupts my workflow

**Comment by drammock** [comment]
If you can find a way to have them collapsed by default on our examples/tutorials but expanded by default elsewhere, PR welcome.

**Comment by hoechenberger** [comment]
It's clearly a UX bug. If this was intended and cannot be changed, it should be reverted.

**Comment by drammock** [comment]
> It's clearly a UX bug.

I could just as easily say "it's a UX bug to have 80% of the screen height filled with `Info._html_repr_` output on many of our tutorials."

> I gave justification why I tagged as a bug

"I really dislike it and it disrupts my workflow" is not the same as "this is not functioning as intended".

**Comment by hoechenberger** [comment]
I didn't break it, I ain't gonna fix it. This is not cool, @drammock!!

**Comment by cbrnr** [comment]
Let me steer the discussion back to the issue, whether or not it should be labeled as a bug is not essential, as is whether or not the behavior is intentional.

Arguably, the new behavior is a regression in terms of usability. Previously, users could rely on the HTML repr to get information on various MNE objects in their interactive notebook workflow, but now all information is hidden behind extra mouse clicks. If it is not possible to expand all sections by default, I think this change should be reverted.

**Comment by larsoner** [comment]
Since these `__repr__`s are an interactive thing one easy way out of this is to have a `MNE_HTML_REPR_COLLAPSED` config var. We'd set this to `1/true` when building doc but leave as `0/false` by default. If we don't think end users will want use this, though, we could accomplish the collapse-during-doc-build-only functionality pretty easily (I think / hopefully) using private variables.

**Comment by cbrnr** [comment]
I think collapsing is really only necessary in the docs.

**Comment by larsoner** [comment]
Okay, solution in progress...
