### ISSUE TITLE
BUG: Inconsistent Welch results by API

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#12582]
### Description of the problem

If you use `inst.compute_psd` with default arguments, you get very different results compared to if you do `mne.time_frequency.psd_array_welch`.

### Steps to reproduce

```Python
import mne
from mne.datasets import sample

data_path = sample.data_path()
meg_path = data_path / "MEG" / "sample"
raw_fname = meg_path / "sample_audvis_filt-0-40_raw.fif"

raw = mne.io.read_raw_fif(raw_fname)

evoked = mne.EvokedArray(raw.get_data(), raw.info)

psd = evoked.compute_psd(method='welch', average=False)
print(psd.shape)

psd2, freqs = mne.time_frequency.psd_array_welch(
    evoked.get_data(picks='data'), evoked.info['sfreq'], average=False)
print(psd2.shape)
```

### Expected results

The same shape output.

### Actual results

compute_psd : (366, 1025, 20)

psd_array_welch: (366, 129, 162)

### Additional information

cc @drammock since I think this relates to changes you've made.

**Comment by larsoner** [comment]
To me it looks like "just" a difference in "n_fft" default. And `psd_array_welch`'s default of 256 is pretty small for typical data, and `compute_psd`'s default of 1024 is better. But it's odd that the [`evoked.compute_psd`](https://mne.tools/stable/generated/mne.Evoked.html#mne.Evoked.compute_psd) docs don't mention that the default is different. We should document where the defaults of `compute_psd` differ from the `psd_array_*` methods (might just be `n_fft`?) in `compute_psd` then we're okay I think. (The default of 1024 is better in my mind than 256 so don't want to change that, and doesn't seem worth it to change `psd_array_welch` to match by deprecation.)

**Comment by alexrockhill** [comment]
I only see the 256 default documented in `psd_array_welch`, I don't see 1024 mentioned anywhere although that seems to be the case from the data but maybe I'm just missing it

**Comment by drammock** [comment]
The `n_fft` default for `compute_psd()` is actually data-dependent and was inherited from the legacy `plot_psd()` and `plot_psd_topo()` functions. It is:

https://github.com/mne-tools/mne-python/blob/43414ba878ee7746464a8fd5aa7f4a555ea0bd5e/mne/time_frequency/spectrum.py#L284

I'll add a docstring note about the default.

**Comment by alexrockhill** [comment]
What do you think about changing the default in `mne.time_frequency.psd_array_welch` to match @drammock ? I agree with @larsoner that that tends to be rather few points for how high sampling rates tend to be nowadays but I'm not overly opinionated. I am a bit opinionated that I don't particularly like how two seemingly synonymous APIs don't have the same defaults, I think ideally they'd be the same.

**Comment by alexrockhill** [comment]
So no to harmonizing?

**Comment by drammock** [comment]
> So no to harmonizing?

Sorry I didn't see your comment before the PR was merged.  My feeling is: the default that uses `min(n_times, 2048)` is a nice convenience default to avoid folks seeing scipy warnings. Folks who are using the `psd_array_*` interface are already doing "advanced" things (working outside of our normal MNE objects) so they might actually not appreciate a default that does a bit of magic like that (i.e., they might prefer to see those warnings). So I would want users to be able to turn it off, meaning the `psd_array_welch` function would need a new `n_fft="auto"` or so (so that passing an integer would *not* suppress warnings, but "auto" would adapt the value to the data size if necessary, thereby preventing the warning).

Which all feels a bit too... over-engineered? Folks doing advanced things can just write the `min(n_times, 2048)` or whatever into their own scripts.

**Comment by alexrockhill** [comment]
Hmm don't love it but I don't really have a better idea at the moment, I think the documentation will go a long way so thanks for that.
