### ISSUE TITLE
Return generated filenames when saving (splitted) instances

### ISSUE THREAD

**Issue by vferat** [mne-tools/mne-python#12809]
### Describe the new feature or enhancement

While saving a large instances, MNE can generates multiple filenames based on the `split_naming` strategy. However, to my knowledge, there is no direct way to get the access to the generated filenames. 
In my current work, I would like to keep track to all generated files ( copying files before temporary folder deletion / before container exit),. Having a direct access to the generated filenames would avoid dirty workaround (i.e. scanning a folder with a template filename).

This feature may also be implement for instances other than raws.

### Describe your proposed implementation

Either or both:

- Output the generated filenames when calling the` raw.save() `method ( by default or with a `return_filenames` parameter)
`filenames = raw.save('fname-raw.fif')`

- Update the `raw.filenames` attribute on save
```
raw.save('fname')`
raw.filenames
('path/to/fname_split-01-raw.fif', 'path/to/fname_split-02-raw.fif')
```

### Describe possible alternatives

the dirty workaround

**Comment by larsoner** [comment]
I don't think we'd want to update `raw.filenames` since I think it would have unintended side effects in some cases. A `return_filenames` would be okay, but I think actually in this case since we currently don't return anything I think it's okay for us just change the behavior from implicitly returning `None` to returning a tuple of the generated filenames.
