### ISSUE TITLE
ENH: add support for text in report.add_section

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1443]
cc @mainakjas

**Comment by Eric89GXL** [comment]
@dengemann don't we have this now, or no?

**Comment by mainakjas** [comment]
I think we have it thanks to @teonlamont. Can you confirm @teonlamont ?

**Comment by teonlamont** [comment]
technically yes. you can add any arbitrary html code to the report. currently, you would need specify the divs, formatting, etc. I think that might be a feature worth having, something like `render_text`. it takes a str or list str, font size, and style (regular, bold, italic) and renders a proper section for the report. I haven't written html since the days of geocities, so if anyone else is inclined, that might be nice :)

**Comment by dengemann** [comment]
Not critical for the release. Change to 0.10

**Comment by teonlamont** [comment]
closing for #1994
