### ISSUE TITLE
preload_data is only for RawFIF

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2040]
I was just working with a RawEDF and I went to call `raw.preload_data`, but I noticed that this method didn't exist for this Raw class. It's currently only implemented for RawFIF. I also saw that there is a new (to me at least) parameter in `_read_segment` called `data_buffer` that is being used whereas the other modules don't have this. should we use this method's use?

**Comment by agramfort** [comment]
as you can now load edf data without preloading yes we could add this
method. It means all raw classes should properly implement it. Clearly not
an issue for v0.9 but maybe a rainy sunday afternoon...

**Comment by Eric89GXL** [comment]
@agramfort AFAIK only EDF and FIFF allow not preloading data. If that's the case then `preload_data` should automatically work for the other backends because they automatically set `self._preloaded = True` or whatever the property is, and `raw.preload_data()` checks that (or should check for it) and returns if data are already preloaded. So it should just be a matter of moving the method to `Base` and making sure it works with EDF.

**Comment by agramfort** [comment]
can you give it a try?

**Comment by Eric89GXL** [comment]
Yeah, maybe today or later this week
