### ISSUE TITLE
log underflow in mne.stats.linear_regression

### ISSUE THREAD

**Issue by TalLinzen** [mne-tools/mne-python#2056]
_fit_lm returns a quantity called mlog10_p_val for easier plotting of p-values. this fails when the p-value is 0.

https://github.com/mne-tools/mne-python/blob/master/mne/stats/regression.py#L134

one possible solution would to have some reasonable minimal p-value, e.g. instead of
```python
mlog10_p_val[predictor] = -np.log10(p_val[predictor])
```

you could do something like

```python
mlog10_p_val[predictor] = -np.log10(np.clip(p_val[predictor]), 0.0000000001, 1))
```

**Comment by dengemann** [comment]
This is a dupe. See #1917.  Yeah, I think we should do something along the lines proposed by you, maybe using ```np.finfo(np.float64).tiny
```

**Comment by agramfort** [comment]
+1 for using np.finfo. min pvalue should be around 1e-14

**Comment by dengemann** [comment]
@TalLinzen PR welcome :)

**Comment by TalLinzen** [comment]
sure, though if the min pvalue is around 1e-14 and `np.finfo(np.float64).tiny` is 2e-308 (on my computer) then it might be better to go for 1e-14, no?

**Comment by TalLinzen** [comment]
hmm on a second thought I'm not sure what you meant when you said that the min pvalue is 1e-14. ;)

**Comment by agramfort** [comment]
try:

In [1]: np.finfo(np.float64).eps
Out[1]: 2.2204460492503131e-16

**Comment by Eric89GXL** [comment]
`tiny` probably has to do with the smallest double precision floating point value before going denormalized, whereas `eps` should be the smallest `d` for which `1 + d > 1`. `eps` probably makes more sense as a meaningful value in this context, but it could actually prove to be too large since eventually we deal with the `log10` of the value -- that will depend on the specific calculations being done to calculate `p`. I guess we could start out with `eps` and if we decide it's clipping too many values, change it to `tiny`. Hopefully it won't matter which one we use either way.

**Comment by teonlamont** [comment]
is there a solution for this? I just got the same RuntimeWarning
