### ISSUE TITLE
dataset updates with partially downloaded dataset

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#2719]
As discussed in https://github.com/mne-tools/mne-python/pull/2717

If a dataset is updated and a part zip file exists from a previous version of the dataset, then the download won't resume. Partially downloaded datasets are probably not as uncommon because our datasets are pretty huge.

**Comment by agramfort** [comment]
can we detect that? using hash?

**Comment by Eric89GXL** [comment]
Hash the partially downloaded version?

**Comment by agramfort** [comment]
>
> Hash the partially downloaded version?


euh no. that would not work. hash something? :)
or use the hash on the tmp file name?

**Comment by jasmainak** [comment]
I thought for a bit about this. You could have a file which stores hashes for 1000 chunks of the data (so 0.1% of the data). First this file is downloaded (and hopefully this would be accurate because it's a small file ~53 kB as I calculated). Then you can verify hashes for these chunks. If download stops, start from the chunk where the hashes don't match. Wdyt?

**Comment by agramfort** [comment]
we could fix it yes but maybe we have more urgent priorities?

**Comment by Eric89GXL** [comment]
To me that additional maintenance burden (more steps for dataset update)
isn't worth the tradeoff given what I assume is the low incidence of this
problem.

We come update the download filename with each update, and delete the old
version. Then at least we wouldn't get any errant restarts.

I suspect this is a problem that has minimal impact on most people (what is
the probability others have hit it?). Mainak I know the issue has affected
you, but as an experienced dev you are both more likely to hit the issue
due to needing updates, and also better equipped to deal with it manually
each time. So my vote is to keep things simple if we can.

**Comment by jasmainak** [comment]
sure, I am not pressing for this. By the way, do we have to to update the hash every time we update the dataset?

**Comment by Eric89GXL** [comment]
> do we have to to update the hash every time we update the dataset?

Yeah

**Comment by jasmainak** [comment]
okay cool. closing.
