### ISSUE TITLE
ENH: coregistration instance without file

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2772]
When using the coregistration, the `inst` param can only be a file. It'd be great if it accepted actual instances too (@christianbrodbeck ?)

e.g.

```
from mne.gui import coregistration
coregistration(inst=raw)
```

**Comment by agramfort** [comment]
+1

**Comment by christianbrodbeck** [comment]
Hm, I think that would require some redesign of the model because the relation from filename to object is built into the traits model currently

**Comment by kingjr** [comment]
Any foreseeable progress on this?

**Comment by Eric89GXL** [comment]
In theory this should be doable, all you need is a good `info['dig']`. So we could make it so that the trait is actually `Instance(Info)` or better eventually `Instance(Digitization)`, and you'd pass `inst.info['dig']` to it. I'll mark it as part of the digitization stuff and hopefully tackle it soon.

**Comment by larsoner** [comment]
Copied this over to #3934
