### ISSUE TITLE
"Morph" dipole to MNI space

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#3525]
we have a vertex_to_mni  function for source space based inverse methods

it would be great to have the same thing for dipole fits. E.g.

dipole.to_mni() -> returns new Dipole instance where dipole.pos is in MNI coordinates.

thoughts?

**Comment by Eric89GXL** [comment]
Probably requires something like #3527

**Comment by Eric89GXL** [comment]
@agramfort do you have an API in mind? I'm thinking:
```
dip.to_mni(subject)
```
Where `subject` is a FreeSurfer subject name.

Unfortunately the dipole fits are not necessarily constrained to a cortical surface, so I think we need to use volumetric / MRI coregistration instead of surface-based coregistration to get there. Agreed?

**Comment by Eric89GXL** [comment]
... oh wait, I think each FreeSurfer subject already has an MNI transform. So this should be very simple actually, assuming I have the API right.

**Comment by agramfort** [comment]
yes it MNE would be great to we could overlay this with the FSL MNI brain
template

dip.to_mni works for me

**Comment by vagechirkov** [comment]
I would like to try to solve this issue (sprint 2021) :)

**Comment by sappelhoff** [comment]
closed in #9091
