### ISSUE TITLE
Rename and relocate `get_edf_events`

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#4497]
I just noticed that we now have a new function `mne.io.get_edf_events`, which is used to extract events from the EDF family. I was thinking two things:  
1. shouldn't this belong at the top level mne. The logic behind this is that we have the function `mne.find_events` which exists there. 
2. this should be renamed `find_edf_events` to follow the naming pattern.

**Comment by agramfort** [comment]
edf events are more like annotations with onset, duration + description. I
think it's a mistake to call them events which are different for MNE/Epochs
etc.

**Comment by larsoner** [comment]
This was introduced this cycle so if we're going to change the name we should do it ASAP to avoid needing to deprecate

**Comment by cbrnr** [comment]
Unfortunately, EDF/BDF files can have events encoded either (or both) as a stim channel or in an event table. Whereas `mne.find_events` works only on the stim channel, `mne.io.get_edf_events` relies only on the event table. I'm not sure if renaming it to `find_edf_events` is a good idea, because people might get confused as to which function to use for EDF files. Granted, people could already be confused by these two functions right now, but `mne.find_events` works for all kinds of file types whereas `mne.io.get_edf_events` only works on the EDF family, which is why it should probably stay in the `io` package.

**Comment by agramfort** [comment]
I think find_edf_events naming is more consistent

I agree it should stay in the io module

**Comment by cbrnr** [comment]
@jaeilepp?

**Comment by agramfort** [comment]
@jaeilepp <https://github.com/jaeilepp> is gone and back home in Finland
... he left my group :'(

**Comment by cbrnr** [comment]
Oh, I didn't know that - he added this new method recently. I can create a PR and rename it (but leave it in `io`) if you want.

**Comment by agramfort** [comment]
please do
