### ISSUE TITLE
eeglab latency to event without sfreq

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#4944]
when working on annotations to events I realize that the eeglab reader
convert `eeg.latency` to sample index with `int(latency)`

see: https://github.com/mne-tools/mne-python/blob/master/mne/io/eeglab/eeglab.py#L697

reading https://sccn.ucsd.edu/wiki/Chapter_03:_Event_Processing it seems that latency is in seconds to converting to events would require `sfreq`

@jona-sassenhagen @smgutstein  @mmagnuski thoughts? is this a bug?

**Comment by agramfort** [comment]
have a look at https://github.com/mne-tools/mne-python/pull/4936

**Comment by mmagnuski** [comment]
@agramfort - latency is stored in samples in eeglab. But then different guis and functions use sometimes ms, sometimes s and sometimes samples.

**Comment by mmagnuski** [comment]
The only issue might be matlab vs python indexing (if that is not dealt with when reading latencies).

**Comment by mmagnuski** [comment]
And it seems that it is not taken care of in _read_annotations_eeglab:
`onset = [event.latency for event in eeg.event]`

**Comment by agramfort** [comment]
event.latency has digits after the commas in our test file so it does not suggest it's samples but more seconds.

can you investigate with one of your files?

**Comment by mmagnuski** [comment]
The file might have been downsampled - then events are then represented as happening between the samples in some cases. I can test that later today but I am almost 100% sure these are samples. But I'll check indexing offsets.

**Comment by agramfort** [comment]
please have a look as there is something currently maybe broken.

**Comment by mmagnuski** [comment]
I confirm that eeglab latency is in samples and that there is a one sample error caused by 0-based indexing in python and 1-based indexing in matlab. I can open a PR in the evening.

As I earlier mentioned - after resampling eeglab event latencies are often between the samples so `latency` becomes a float, not int. We should take care of this too - if currently we just cast these values to int, we can have other single sample errors. When `latency` is for example 2015.8 and it is cast to 2015 integer (or rather - 2014, given indexing differences between matlab and python :) ).

**Comment by mmagnuski** [comment]
There are some points mentioned here that are left to adress - one of which is dealing with float latencies. Should I open a separate issue about that or should we leave this one open?

**Comment by agramfort** [comment]
Open a new issue
