### ISSUE TITLE
corrmap titles are bad again

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5009]
I don't know why yet, but something changed that results in corrmap again having bad axis titles.

I'll eventually take care of it.

**Comment by drammock** [comment]
Closing because the fig and subplot titles look fine to me here (and there are no axis titles): https://mne.tools/dev/auto_tutorials/preprocessing/plot_40_artifact_correction_ica.html#selecting-ica-components-using-template-matching

@jona-sassenhagen feel free to re-open if you disagree, and explain how you think they should look.
