### ISSUE TITLE
Add support for XDF (labstreaminglayer format)

### ISSUE THREAD

**Issue by dmedine** [mne-tools/mne-python#5180]
I think this should be added. I am happy to do this. There is already a python loader for the xdf format so it is just a matter of making output structure compliant with mne.

**Comment by dmedine** [comment]
Ok. I'll put this on my todo list and submit a PR when it is done.

**Comment by sappelhoff** [comment]
That's a good idea. In the repo for the python XDF loader, there is an ongoing discussion to make a "pyxdf" package, however the discussion is stagnating a bit. Mainly because there is a lack of tests for the robustness/reliability of the loader. See [here](https://github.com/sccn/xdf/pull/10) for the discussion.

Integrating the xdf loader into MNE would not circumvent the issue of (so far) lacking tests, but maybe the stagnation is over now :-)

**Comment by cbrnr** [comment]
@sappelhoff I think MNE would be a great place for the XDF loader!

**Comment by larsoner** [comment]
I thought that we discussed this somewhere, but a low-order spline interp (or even linear!) would probably be sufficient. So I don't see this as too big a hurdle.

**Comment by cbrnr** [comment]
Yes, it shouldn't be too difficult, just wanted to bring this up in case this was not obvious. Can you confirm that all signals must have the same sampling frequency? If so, how do we choose which sampling rate to resample to? Most XDF files have nominal sampling rates for each stream, so we could resample to the highest.

**Comment by larsoner** [comment]
> Can you confirm that all signals must have the same sampling frequency?

Yes

> If so, how do we choose which sampling rate to resample to? 

Resampling to the highest data channel rate (by default, we could make different options with ``resample='auto'`` kwarg) makes sense to me. In practice I imagine these will all usually match anyway.

**Comment by sappelhoff** [comment]
There are some developments with the python reader for XDF files. Soon, there might be a pip installable package, see: https://github.com/sccn/xdf/pull/21

That would make this issue easier to solve.

**Comment by trmullen** [comment]
this is a great idea, and we would be happy to support this initiative!

**Comment by cbrnr** [comment]
@dmedine @trmullen do you have time to work on this?

**Comment by sappelhoff** [comment]
@cbrnr check out the discussion in the XDF issue linked above, specifically there is probably the need for some MNE decision on this statement from @dmedine:

> I said a long time ago that I would shove xdf into MNE. The issue there (if I understand correctly) is that if there are multiple streams, they all have to have the same sampling rate, first time-stamp, etc. This makes it labor intensive enough for me to avoid doing it. **However, if MNE is like EEGLab and it is content to grab only EEG and marker streams, then this might not be such a chore after all.**

@larsoner @agramfort 

Personally, I think that being able to extract an EEG stream from XDF is better than nothing and worth an implementation. An even better solution would be to allow the extraction of *any* single stream out of the XDF file.

... the "best solution" of reading the complete XDF file with all its streams seems tricky indeed

**Comment by cbrnr** [comment]
I thought that the existing XDF reader already supports synchronizing time stamps from different streams, so this is one problem already solved. Grabbing a single stream is straightforward, because all streams are returned in a list of dicts, of which we'd need the values for the `'time_series'` and `'time_stamps'` keys.

**Comment by agramfort** [comment]
MNE only supports "streams" with the same sampling rates. So yes if we can
read the EEG data and mimic what we have already for edf files +1

I also feel that we need more integrated efforts between pyedf, pybv,
pyxdf, neo and MNE to avoid duplication of efforts. I am sure I have time
though to coordinate these efforts. It would be a great topic for a code
sprint.

**Comment by cbrnr** [comment]
Yes, absolutely! I also have the feeling that we could greatly benefit from closer collaboration. I'm already involved in MNE and pyxdf, so I could at least try to coordinate a bit.

**Comment by dmedine** [comment]
Just to clarify, the XDF reader does synchronize the time stamps in that 
it puts all the streams on the same timebase, but it does not resample 
the data. So time 3.14 in stream A is the same as 3.14 in stream B, but 
they might have completely different sampling rates. Is this also an 
issue for markers, by the way?

**Comment by dmedine** [comment]
I currently don't have time to work on this, but I can probably devote 
some in the future.

**Comment by cbrnr** [comment]
Resampling to a common sampling rate shouldn't be a big issue as long as we start from tmin and include all time points up to tmax.

**Comment by agramfort** [comment]
for my curiosity how do you remap to the same time stamps? do you
interpolate? how do you decide the regular grid of time samples?

**Comment by cbrnr** [comment]
Yes, I'd resample all signals to the highest sampling rate, this will create samples at the same time points. In SigViewer, we do that, but the user can change the resampling rate if the one we choose automatically is too high. If the starting points differ, we add zeros to the signals starting later.

**Comment by dmedine** [comment]
The way LSL puts everything on the same time base is fairly complicated. 
I will try to summarize it in broad strokes.

Basically, when data is being streamed by an outlet into an inlet, there 
are periodic handshakes between inlet and outlet that return the time 
difference between the CPU clock times between the two. The algorithm 
for doing this is canonical and based on the NTP method for doing the 
same. In the LSL recording program, these offsets are written into the 
footer of the data file as the streams are being recorded. Meanwhile 
each datum is also timestamped based on its own CPU time. Then, when the 
file is loaded, the loading program (implemented in Matlab and Python) 
uses this information to form a piecewise linear map between the 
timestamps in each incoming stream and the write times in the recording. 
This corrects the slowly drifting time offsets between various sending 
CPU times and the CPU time of the recording.

If the stream is coming in at a regularly sampled sampling rate (e.g. an 
EEG stream, not an arbitrary marker stream) the differences between 
successive timestamps are also smoothed to correct for jitter. The end 
result is a data structure that has the data for each stream and its 
corresponding, corrected, timestamp values. These streams are then said 
to be synchronized. This has been validated to provide sub-millisecond 
accuracy. This doesn't align the samples to a common grid. That would, 
of course, require an interpolation step, which is the part that I don't 
have time to work on right now. This would, now that I think about it, 
perhaps be a nice feature to add to the LSL loading software. So far as 
I know, no one has ever requested this.

What isn't corrected for (it must be measured) is the lag time between 
hardware acquisition and the time the data gets timestamped. There are 
various means of measuring these relative latencies, but it isn't always 
so straightforward. Back in the day this required a fair amount of 
handmade microphones, photo-diodes, and buckets of salt water. Brain 
Products (shameless plug) sells hardware (StimTrak 
<https://www.brainproducts.com/productdetails.php?id=57>) that can 
provide these measurements through sending hardware triggers. NBS also 
sells a product (which is LSL based) called the LabStreamer 
<https://www.neurobs.com/menu_order/purchase_labstreamer> that helps 
measure these hardware latencies.

One last detail is that LabRecorder (the LSL recording program) picks up 
each stream on a separate thread so they always have a different start time.

**Comment by agramfort** [comment]
thanks a lot for clarifying

then for MNE what we need is a way to resample all streams we want to read
to the same sampling freq
like we do for EDF reader.

**Comment by trmullen** [comment]
Hi @cbrnr -- yes happy to assist with this effort.

Tim

**Comment by jasmainak** [comment]
Not adding much to the discussion. But cross linking to [related discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bids-discussion/NeqFO-lJhsc/_atcTFfIBQAJ) on BIDS mailing list

**Comment by cboulay** [comment]
pyxdf is now available with `pip install pyxdf`

**Comment by cbrnr** [comment]
As an initial implementation, what about allowing only one regularly sampled stream (plus optionally any number of marker streams)? That way, we don't have to resample and we can directly use time stamps and data samples provided by `load_xdf`. Optional marker streams could be converted to annotations. This would probably cover many use cases already, and would be a lot better than what we currently have (nothing).

**Comment by agramfort** [comment]
>
> As an initial implementation, what about allowing only one regularly
> sampled stream (plus optionally any number of marker streams)? That way, we
> don't have to resample and we can directly use time stamps and data samples
> provided by load_xdf. Optional marker streams could be converted to
> annotations. This would probably cover many use cases already, and would be
> a lot better than what we currently have (nothing)
>
no objection but I would start with a gist

**Comment by cbrnr** [comment]
Here's a first proof-of-concept implementation: https://gist.github.com/cbrnr/7164a12868bc7616056587a41f51e92d

Basically, it loads the first EEG stream it finds and adds the first marker stream if present. For many XDF files, https://github.com/sccn/xdf/pull/42 should be fixed before this works. Comments and suggestions welcome!

**Comment by agramfort** [comment]
would this work with preload=False?

>

**Comment by cbrnr** [comment]
Because XDF is a format designed for streamed data, `preload=False` would require to parse the whole file. This is certainly doable, but I think it should be implemented upstream. What other requirements does MNE impose on readers? Blockwise random access reading?

**Comment by cbrnr** [comment]
Because XDF is a format designed for streamed data, `preload=False` would require to parse the whole file. This is certainly doable, but I think it should be implemented upstream. What other requirements does MNE impose on readers? Blockwise random access reading?

**Comment by larsoner** [comment]
> What other requirements does MNE impose on readers? Blockwise random access reading?

In general yes, one should at a minimum (that I can think of):

1. Populate `info` properly,
2. Give the number of samples in the file, and
3. Provide a function that returns an arbitrary chunk of data for a given `start, stop` sample number pair

If these are provided, all methods of `BaseRaw` should work (I think!).

If they are not / cannot be provided, we'd have to think about how to deal with this.

**Comment by cbrnr** [comment]
I think all of these points can be implemented, but only with `preload=True`. XDF makes it really hard to randomly access a portion of data, because it does not reserve a constant amount of bytes per data segment. In any case, jumping around the file is still reasonably fast using boundary chunks, but since these are optional the worst case scenario is that the file must be searched from beginning to end. All of this should be provided upstream, but currently `load_xdf` always loads everything.

**Comment by agramfort** [comment]
pyedf or pyxdf don't support random access of chunks at all? I don't have a
strong feeling on this but that would make a precedent to have readers that
don't support preload.

>

**Comment by cbrnr** [comment]
`pyedflib` does support random access, that is you can specify the channel, start time, and end time. I think XDF is really an exception here - I don't know any other file format that's structured similarly, so this might be the only reader for now.

**Comment by cbrnr** [comment]
I've added a `parse_xdf` function that does a quick pass over the whole file to read just the headers (but ignore all actual content). This is very fast even for large files (fractions of a second) as compared to the complete `load_xdf` call, which can take several seconds. Maybe we can use `parse_xdf` to fill our meta info even in the case of `preload=False`. But once data is actually needed, we'd need to pull in everything, so it's just a simple lazy loading without random access.

**Comment by agramfort** [comment]
not strong feeling here. Do you need this to process your own data? or some
public data?

>

**Comment by cbrnr** [comment]
I don't even work with XDF myself, but I have been involved with the format and I also needed it in SigViewer. But I'm not sure if this was your question...

**Comment by tstenner** [comment]
> In general yes, one should at a minimum (that I can think of):
>
> 1.    Populate info properly,
> 2.  Give the number of samples in the file, and
> 3.    Provide a function that returns an arbitrary chunk of data for a given start, stop sample number pair

All of these require at least one full pass over the file because the number of streams and samples isn't known in advance. Also, with postprocessing the number of samples might change, even for evenly sampled streams.

I'm not an expert, but I think the postprocessing in the current implementation needs all samples and can't just take a time slice, select all chunks which fall into that range and then read only those samples. Plus, the default of a few seconds of data per chunk means that most operations will need to read multiple chunks so preloading might make everything a lot simpler and faster, even if only a subset of data is needed.

**Comment by cbrnr** [comment]
> All of these require at least one full pass over the file because the number of streams and samples isn't known in advance. Also, with postprocessing the number of samples might change, even for evenly sampled streams.

Yes, but the pass is much quicker with `parse_xdf` (i.e. when you don't process the contents). Maybe we can use this to fill our meta info when `preload=False`.

> I'm not an expert, but I think the postprocessing in the current implementation needs all samples and can't just take a time slice, select all chunks which fall into that range and then read only those samples. Plus, the default of a few seconds of data per chunk means that most operations will need to read multiple chunks so preloading might make everything a lot simpler and faster, even if only a subset of data is needed.

Correct, once you start working with the actual data, everything needs to be read and processed (clock synchronization). So basically random access just won't be possible.

**Comment by cbrnr** [comment]
BTW, `read_raw_xdf` in https://gist.github.com/cbrnr/7164a12868bc7616056587a41f51e92d also supports loading arbitrary streams by name (and since names need not be unique I could/should also add loading by stream ID). If no name is provided, the first EEG stream is used.

**Comment by larsoner** [comment]
I'm okay with only allowing preload=True or string for this format then

**Comment by massich** [comment]
in `0.17.1` this is already the case that we can only read with `preload=True`. i.e: edf files with annotations.

**Comment by agramfort** [comment]
ok fair enough then. I assume we can use as soft dep
https://pypi.org/project/pyxdf/ ?

**Comment by cbrnr** [comment]
We could, but this should be discussed again. It looks like MNE is much more actively maintained than pyxdf, so we could also think about integrating the XDF code directly into MNE. I'd prefer this.

**Comment by agramfort** [comment]
I would prefer to boost the maintenance team of pyxdf and eventually pyedf
to distrbute the maintenance load. It would scale if we always integrate
the community work.

>

**Comment by sappelhoff** [comment]
Couldn't you get write permissions for pyxdf @cbrnr ? That would at least remove potential "blocks" due to inactivity from the reviewing / merging side of PRs at pyxdf?

**Comment by cbrnr** [comment]
I'd hope that I could (@cboulay WDYT?), but I can't just rage-merge everything without review 😛 - but it would certainly help if I was more directly involved.

BTW, is there a way I can list all GitHub repos I have write access to?

**Comment by cboulay** [comment]
I've been explicitly told that I cannot add any new people to SCCN repos. I recently asked for help and guidance, because it's clear that xdf requires more stewardship than it currently receives (and I don't have time to give), and I received a couple "Chad's right, we need more work on this" and a couple no-answers.

One of my ideas, which was not well received by the xdf oversight committee (*real people but not a real committee), is to break out xdf into submodules just how we did it for labstreaminglayer. Then we can have individuals working with more authority on the code while not granting them the ability to break SCCN's repositories. i.e., any changes that happen upstream in these submodules will not be visible to sccn/xdf users until someone with SCCN authority updates the submodule pointers.

Even though there was resistance to this, I went ahead and created the xdf-modules GitHub organization and put in a few placeholders for submodules it will hold. I'm just asking around now about how to move the code without losing the commit history.

I've already invited a few people to the organization, including @cbrnr , but there isn't much to be done yet until we get the code + commit history moved over.

**Comment by agramfort** [comment]
let me share my thoughts on this. If you want xdf to become a community
standard you need to make pyxdf a project that is not affiliated to SCCN.

if you can move the code to a more neutral org it's great. thanks a lot

>

**Comment by cbrnr** [comment]
I think creating separate repos is a step in the right direction (thanks @cboulay for adding me) - I always thought that `pyxdf` shouldn't be combined with MATLAB (and potentially other stuff). I agree with @agramfort, but that's exactly what @cboulay just did - if the new upstream will be xdf-modules/pyxdf, then it is essentially detached from SCCN. In any case, since at least the pyxdf code is BSD licensed, we can always fork it and roll our own thing (that's why I was suggesting to do it in MNE, it's really not that much more to maintain).

**Comment by agramfort** [comment]
forking and maintaining our own code is bad community-wise. It make the
community more fragmented while we should consolidate

>

**Comment by cbrnr** [comment]
Yes, I meant migrating and not forking.

**Comment by cboulay** [comment]
@cbrnr you now have write access to https://github.com/xdf-modules/xdf-Python
I will ask the other people who have made Python pull requests to move their PRs to that repo instead.

**Comment by cbrnr** [comment]
Thanks. BTW, I've never migrated/transferred a repo, but shouldn't it be possible with the standard git commands (i.e. cloning and pushing to the new repo)? https://www.atlassian.com/git/tutorials/git-move-repository

**Comment by cbrnr** [comment]
I've implemented a basic XDF reader in MNELAB:
https://github.com/cbrnr/mnelab/pull/22

There are some caveats (see my comment in that PR), but loading basic EEG streams should work. I'm not sure if we can handle loading multiple streams, because everything gets very slow even with just one long stream (with a high number of channels/samples, e.g. 80 channels, fs 1000Hz, 10 minutes).

**Comment by teonbrooks** [comment]
@cbrnr very cool. it looks like we might be able to incorporate the lazy evaluation of preload and seek on demand. with xdf, can streams be added during recording or we do always know that it would contain certain streams and only those stream throughout?

**Comment by tstenner** [comment]
@teonbrooks New streams can appear anywhere in the file, but per spec the header for the stream has to appear before the data chunks.

**Comment by teonbrooks** [comment]
I guess then you would need to be able to read all the headers first to and construct a map of pointers (sample_n --> data_block_n) for the eeg if you wanted to avoid loading the whole file

**Comment by cbrnr** [comment]
Yes, it is possible to parse the whole file and just consider the data of the stream you want (and skip over the data you don't want), because each stream has a unique stream ID. That's something I'm already doing with `parse_xdf`, but the current version of `pyxdf` (which I use to actually load data) doesn't support this yet.

**Comment by cbrnr** [comment]
@agramfort just thought about your comment - when you say pyxdf should not apparently be associated with SCCN, why is this not a problem with MNE Python hosted at Martinos?

**Comment by agramfort** [comment]
>
> y@agramfort <https://github.com/agramfort> just thought about your
> comment - when you say pyxdf should not apparently be associated with SCCN,
> why is this not a problem with MNE Python hosted at Martinos?
>

mne-python is not hosted on an github org of martinos and it's not
administrated by anyone at martinos
we have the website historically hosted at martinos.org. We use
mne-tools.github.io as nightly build of the doc.
It's true that we have martinos in the url of the website but we have all
the logos of all the institutions
that helped over the years.

**Comment by Ardillen66** [comment]
Hello, 

I would like to know what the status is on this feature in 2020, as it is still open. Are you still planning to include this at some point? I would be very interested in having this feature built into MNE.

Alternatively, it would be nice if you include a link to relevant software in the documentation if you are not planning to include this in MNE. That way people looking for a solution don't have to go to google and read through this issue.

**Comment by cbrnr** [comment]
Currently only [MNELAB](https://github.com/cbrnr/mnelab) supports loading XDF. We don't know if and when this feature will be available in MNE, because there are a couple of open questions (e.g. how do we handle multiple streams with different sampling frequencies). However, in the meantime you can use either [pyxdf](https://github.com/xdf-modules/pyxdf) or even the reader in MNELAB (`from mnelab.io import read_raw`) if you want to work with XDF files in MNE-Python.

**Comment by larsoner** [comment]
FYI I just used `pyxdf` + `mne.io.RawArray` to read an XDF-formatted file (recorded using LSL stream recorder). I think this is what we should probably "support" from the MNE end so that people format data the way they need. @cbrnr would you be up for making a PR to mention using MNELAB and/or `pyxdf` directly to load data and using `mne.io.RawArray`? To me it's the cleanest solution since there are so many ways people's data can show up in XDF format.

**Comment by cbrnr** [comment]
Sure. What would you like me to implement? Just an update to our docs (where)? I'm using the `mne.io.RawArray` approach in [MNELAB](https://github.com/cbrnr/mnelab/blob/caa18e02b42ddd44c8737fe58fe3e7287eb674ac/mnelab/io/xdf.py#L9), so this could be some sort of reference implementation which we could include directly in MNE. However, this supports only one particular stream which users have to select.

**Comment by larsoner** [comment]
> Just an update to our docs (where)? 

Probably update https://mne.tools/stable/auto_tutorials/io/plot_20_reading_eeg_data.html

> I'm using the mne.io.RawArray approach in MNELAB, so this could be some sort of reference implementation which we could include directly in MNE. However, this supports only one particular stream which users have to select.

Yeah I'd rather just show people a little code snippet, probably we are using the same things like:
```
data, header = pyxdf.load_xdf(fn_eeg)
data = data[0]['time_series'].T
info = mne.create_info(...)
raw = mne.io.RawArray(data, info)
```

> this could be some sort of reference implementation which we could include directly in MNE

I'd rather not include an actual implementation in MNE because there is too much flexibility in the format, I'd rather just update the docs to say "something like this might work for your use case" and then people can adapt appropriately based on the data they have.

**Comment by drammock** [comment]
For cases like this (reading in data from a source type that we don't fully support), I think they make more sense as a how-to example rather than integrated as part of the tutorials.  The NEO how-to is an example of this.

**Comment by larsoner** [comment]
If it is a separate tutorial, I think we should at least link to it from the `plot_20_reading_eeg_data.html`, since that's where people will probably naturally end up if they look into file formats in MNE

**Comment by drammock** [comment]
agree... I was just editing my above comment to say something similar.

**Comment by cbrnr** [comment]
@larsoner OK, this tutorial might be a good place to mention it.

I've linked to my reader in my previous comment, but yeah, I'm basically just doing what you are using. However, I'm also reading custom units as well as marker channels, which I convert to annotations. I would mention my function in addition to some general code snippet, because people can just go ahead and use `from mnelab.io.xdf import read_raw_xdf`, which is probably OK for many use cases.

**Comment by cbrnr** [comment]
Full XDF support is now available in MNELAB (currently in the `main` branch, but soon in a new release).

**Comment by rob-luke** [comment]
> Full XDF support is now available in MNELAB (currently in the main branch, but soon in a new release).

@cbrnr 
What's involved in getting "Full" support in to MNE-Python? I just followed the https://mne.tools/dev/auto_examples/io/read_xdf.html tutorial. What is missing from this that would be included in a full xdf reader?

I am now using xdf files and may be able to assist in implementing xdf support in MNE.

**Comment by cbrnr** [comment]
@rob-luke by full support I am referring to importing more than one stream from an XDF file. This requires resampling to a common sampling frequency.

The example shown in the docs requires that one stream is selected.

MNELAB has full support now, which includes importing an arbitrary number of streams plus all marker streams (which are converted to annotations). You can use this function in your own scripts, for example:

```
from mnelab.io import read_raw

raw = read_raw(fname, stream_ids=[1, 3, 5], fs_new=1000)
```

This will load streams 1, 3, and 5 from a file named `fname` and resample them to 1000 Hz. If you want to find out which streams are contained in a given XDF file (and their corresponding stream IDs), you can use:

```
from pyxdf import resolve_streams

print(resolve_streams(fname))
```

All of this could potentially be moved to MNE, but we have not discussed if this should be done. If so, I can do the work, but for now I think it's easy enough to just use the function from MNELAB directly.

**Comment by rob-luke** [comment]
Thanks @cbrnr
I tested out the functions in MNELAB and they worked wonderfully.
Given how robust and well written the function are, can we move this reader to MNE-Python? This will provide  I am able to help in the transition.
Or is there some concern with adding this functionality @larsoner @agramfort ?

**Comment by agramfort** [comment]
no objection

**Comment by cbrnr** [comment]
Then I'll prepare a PR.
