### ISSUE TITLE
[decoding] roc_auc with multiclass (and cross_val_multiscore)

### ISSUE THREAD

**Issue by giuliagennari** [mne-tools/mne-python#5682]
Hello there,
according to scikit learn documentation, when dealing with multiclass problems it is possible (... what about meaningful?) to compute AUC for each class, given that one-vs-rest approach is used. 
Now, I am trying to do that but I am very basic in programming skills, so having a really hard time.
 This is what I have:

```python
from sklearn.metrics import roc_auc_score

clf = make_pipeline(Vectorizer(), StandardScaler(), LogisticRegression(penalty='l1'))
time_decod = GeneralizingEstimator(clf, n_jobs=-1)

time_decod.fit(X_train, y_train)
y_pred = time_decod.predict_proba(X_test)

classes = set(y_test)
scores = list()
for train_tp in range(n_timepoints):
    scores_tp = list()
    for test_tp in range(n_timepoints):
        _score = list()
        for ii, this_class in enumerate(classes):
            _score.append(roc_auc_score(y_test == this_class, y_pred[:, train_tp, test_tp, ii]))
        score = np.mean(_score)
        scores_tp.append(score)
    scores.append(scores_tp)
```

Does it make sense at all/is it correct?
If so, how do I transform this into a function usable with cross_val_multiscore (scoring= ... )? 
I have been trying to do that but I really can't figure it out.

Thank you so so much to anyone giving a little help!

**Comment by massich** [comment]
Not mne realated. Closing. 

Feel free to reopen it at [sklearn's issue tracker](https://github.com/scikit-learn/scikit-learn/issues). If you do so make sure that imported all the needed functions so that mantainers can copy-paste your snipped. (ie make_pipeline, Vectorizer, SandardScaler, LogisticRegression, GeneralizingEstimator are not imported , and `y_test` you have call it `y_pred`)
