### ISSUE TITLE
ica.plot_properties ignores reject dict

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#5815]
when you plot component properties you can specific the reject param used in fit.

reject should be set as attribute of ica object and be used with ica.plot_properties

cc @pierreablin @Okamille @jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
@mmagnuski

**Comment by mmagnuski** [comment]
Ok, so we should add `ica.reject` (or something more verbose?) and then use this parameter automatically in `plot_properties`, right? Some questions then:
* Would you prefer that the data segments be rejected without any sign automatically or should the blanks be visible (nans in epoch's image)?
* Would it be useful to add a parameter to `plot_properties` that allows to ignore the `ica.reject`? In some cases you may want to investigate whether some epochs are worth rejecting (not included in further analyses) although they were not used in ica fitting. 
* Or should it not be automatic and rather a `reject` kwarg should be added to `plot_properties`? It would be explicit to do `ica.plot_properties(..., reject=True)`.
* Should something similar be done in the ica sources plotter? For example 'ignore' annotations showing which data segments were not used to fit ica.

**Comment by jona-sassenhagen** [comment]
>Would you prefer that the data segments be rejected without any sign automatically or should the blanks be visible (nans in epoch's image)?

Yes, maybe reject could default to None or False and the image could then not show the dropped epochs at all? And reject=True means it pulls reject from the ICA object.

I'm not sure how well NaNs play with the smoothing.

>Would it be useful to add a parameter to plot_properties that allows to ignore the ica.reject? In some cases you may want to investigate whether some epochs are worth rejecting (not included in further analyses) although they were not used in ica fitting.

`ica.plot_properties(..., reject=False, ...)`?

**Comment by mmagnuski** [comment]
> Yes, maybe reject could default to None or False and the image could then not show the dropped epochs at all? And reject=True means it pulls reject from the ICA object.

with `False` it would not drop anything as I imagine, so the question about showing which data parts were rejected concerns `reject=True`.

> I'm not sure how well NaNs play with the smoothing.

Right, that won't be good, the NaNs would spread like a disease. It would be possible to reject the segments, then smooth and then add rows with nans to the matrix. I think it might be useful to see what was rejected, but then some people would surely prefer not to, so that might require additional kwarg, so maybe we should think about it later?

> `ica.plot_properties(..., reject=False, ...)?`

Yes, that's what I suggested in the next point (but didn't go back to the previous one to edit for clarity :) ).

**Comment by jasmainak** [comment]
If you want to have a parameter, I would suggest not changing the semantics. The param `reject` has always been a dictionary, so to me changing to be boolean in some parts of the code base is going to be confusing for many users. Why not simply use a rejection dictionary without saving it as an attribute in ica.reject? Is there a strong argument for believing that the rejection dictionary used during the fit is going to be valid for any other epochs for which you do ica.plot_properties ?

**Comment by mmagnuski** [comment]
@jasmainak Yes, that would be simpler. A middle-ground is to to have `ica` save `reject` dict and `reject` in `.plot_properties()` accepting a boolean or a dict.

**Comment by mmagnuski** [comment]
But I'd give my vote to just `.plot_properties(..., reject=some_dict)`.

**Comment by agramfort** [comment]
fully agree with @jasmainak a reject param is a dict or None

if reject was used during fit it must be used by default in
plot_poperties now we can decide if we mark bad epochs in red or
anything else or just ignore them.

+1 however to be able to pass a different reject in the plot_properties method

**Comment by jona-sassenhagen** [comment]
My main point is, I'd consider it very dangerous if plot_properties displays activity as if it had no artefacts. I.e., if you end up dropping all high-variance/high-amplitude epochs, the EOG ICs will look flat. So you will misidentify them.

I.e., I am very skeptical of dropping by default.

**Comment by mmagnuski** [comment]
good point, I agree with Jona.

**Comment by agramfort** [comment]
you could make the dots in the variance plot red and write the percentage
of epochs that have been dropped?

I'd like to see by default what the ICA solver had as input.

**Comment by agramfort** [comment]
any volunteer to give it a try?

cc @Okamille

>

**Comment by Okamille** [comment]
Yep, I'll work on it tommorow :smile:

**Comment by Okamille** [comment]
Maybe we should consider using a reject_args instead of a reject, and include inside 'decim', 'reject', 'flat', 'tstep' and maybe 'picks' i.e channels to be used ?
That is what is used in the ICA object to perform the rejection, and they are not stored as members of the class afterward, so either we store these to perform the 'auto' rejection, or we ask the user to supply these parameters everytime.

**Comment by Okamille** [comment]
![epochs_dropped](https://user-images.githubusercontent.com/25035339/50961965-69f29b80-14c9-11e9-970d-af407fac9035.png)
What do you think about this way of conveying the info ?

**Comment by agramfort** [comment]
I would change the texts. ylabel should be:

`Variance (AU)`
and title
`Dropped segments: 7.4%`

I would have left the red dot at their original values as like this it's hard to know if the reject threshold is conservative or not. @dengemann or @jona-sassenhagen or @mmagnuski any option?

**Comment by mmagnuski** [comment]
I agree, having red dots at zero doesn't tell me much - it may almost suggest that these epochs/segments were flat. 
Also - if we are showing rejected segments with red dots in *variance plot* I would also mark them in the *epochs/segments image*. The best option to do it is in my opinion:
* first calculate the image as previously
* then add rows filled with np.nan where removed epochs were originally

so it shouldn't be much of a problem, because you perform similar inserting for scatter. In case you you wanted to plot image nan elements in a different color than the default [here is a nice example](https://stackoverflow.com/questions/2578752/how-can-i-plot-nan-values-as-a-special-color-with-imshow-in-matplotlib).

**Comment by Okamille** [comment]
![bugfixed](https://user-images.githubusercontent.com/25035339/50977199-0892f280-14f2-11e9-9929-2f125417e803.png)

So what do you think of this proposal ? Rejected values in image are white by default, I can use your tip @mmagnuski if you want another color :)

**Comment by jona-sassenhagen** [comment]
Is the spectrum calculated with the inclusion of missing values?

**Comment by Okamille** [comment]
No, it is computed from the "clean" epochs

**Comment by mmagnuski** [comment]
All looks good. I have only one question:
the variance plot suggests that we have altogether more than 50 segments, and the last segment is rejected. This can't be seen in the image plot: it suggests that there are not more than 50 segments and only 3 are removed (4 in variance plot).

**Comment by Okamille** [comment]
Oh yes, it's weird, I may have made some mistakes when adding the NaNs, I'll look into it

**Comment by jasmainak** [comment]
I would also suggest having consistent color between the subplots (red?) for bad epochs. Maybe work with facecolor and edgecolor to make it work?
