### ISSUE TITLE
CSP questions

### ISSUE THREAD

**Issue by zhoudapeng1234** [mne-tools/mne-python#7482]
I don't understand some steps in the CSP calculation process, maybe someone could answer these questions:

1. Why there is no  "whitening transformation" in the fit process? It is different from the calculate steps in the references 《Optimizing Spatial Filters for Robust EEG Single-Trial Analysis》and 《Multiclass common spatial patterns and information theoretic feature extraction》.

2. Why the eigen_values need to subtract 0.5 before being sorted?
![image](https://user-images.githubusercontent.com/17759040/77167419-ff87b300-6af0-11ea-8da3-ee5a6597624c.png)

**Comment by agramfort** [comment]
ping @alexandrebarachant @cbrnr

**Comment by cbrnr** [comment]
@mbillingr I think you wrote some of the CSP code - can you answer these two questions?

**Comment by mbillingr** [comment]
Amazing how the most "obvious and self-explanatory" code turns into "WTF did I think?" after a couple of years...

1. I can't answer the first question; it has been too long that I have read the papers. Do the papers say anything about why the whitening transform is required?

2. This is an obscure way of rearranging the sorted eigenvalues. I believe it was meant to separate the patterns associated with the two classes.

**Comment by larsoner** [comment]
Looks like (2) was fixed by #8151, the whitening issue I'm not sure about

**Comment by catalinamagalvan** [comment]
About (1), the calculation steps are here very similar to the ones in 《Optimizing Spatial Filters for Robust EEG Single-Trial Analysis》. The only difference I see is that in this function the generalized eigenvalue problem solved is:

`eigen_values, eigen_vectors = linalg.eigh(covs[0], covs.sum(0))`

instead of

`eigen_values, eigen_vectors = linalg.eigh(covs[0], covs[1])`

that would be strictly the same of the papers, but both are equivalent.

**Comment by larsoner** [comment]
I think the questions have been answered and if not, nowadays https://mne.discourse.group/ is the place to go to discuss them (and then maybe open a PR to improve our docs)
