### ISSUE TITLE
ENH: proposed improvements to plot_psd_topomap

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7586]
Some things I wished I was able to do when using `epochs.plot_psd_topomap` yesterday, and some ideas about how to implement them:

1. **automatic joint determination of vlims.** copy over the API from #6922 that allows `vlim='joint'` for multi-topomap figures

2. **logarithmic colormap.**  SSVEP carrier frequency ought to have more power than oddball frequency, by virtue of the experimental design (fewer oddball stimulus exposures).  A logarithmic colormap might help make the carrier & oddball spikes both visible given the same vmin/vmax.  In addition to the sharp SSVEP spikes, the data I'm currently working with has a large broad bump in the spectrum, with power roughly an order of magnitude greater than the spikes (probably a muscle artifact).  A logarithmic colormap would make it possible to plot that in the same figure with the spikes (useful during exploratory analysis).

3. **make it easier to plot a specific frequency bin.**  Because SSVEP leads to very focal spikes in the spectrum, the current API of `bands=[(band1_lower_edge, band1_upper_edge, 'subplot title'),]` is a inconvenient. It would be nice to be able to pass a specific single frequency and have it not fail. Possible API ideas:
    - pass in a single frequency, get back a topomap of the single bin nearest to that frequency
    - pass in a single frequency and a bandwidth
    - pass in a single frequency and an integer number of bins

For comparison, currently to get a single bin topomap you have to compute the bin spacing and pick bin lower/upper edges that are ± half a bin width from the target frequency. But knowing the bin spacing requires computing the PSD first before plotting (and the PSD then gets computed again within the plotting function, which is not very efficient).

**Comment by larsoner** [comment]
For (1) agreed

For (2) this should probably be an option, +1 for making it the default since it's closer to what we do when plotting PSDs anyway

For (3) I like the first idea, just get the single bin nearest to that freq. I don't love the integer number of bins because it's not a natural unit of measurement. We could enable the second idea, too, which would make a float `bands` (first idea) basically just get upconverted to `(bands, 0)` in the code (assuming you always make sure you get at least one band in your freq += bw limit).
