### ISSUE TITLE
Spherical searchlights as labels for all vertices in source space

### ISSUE THREAD

**Issue by olafhauk** [mne-tools/mne-python#8517]
#### Describe the new feature or enhancement
I would like to use spherical searchlights as labels for all vertices in source space to compute PSFs/CTFs for sources with spatial extent (rather than point sources). I tried to use mne.grow_labels(), but it produces the error "NotImplementedError: Can't produce more than 1024 unique colors". 

#### Describe your proposed implementation
Could one implement an option like '''colors=False''' to prevent the error message?

#### Describe possible alternatives
Possible workaround: One can use list comprehension to call grow_labels per vertex/seed, but I don't see a reason to limit it to 1024 colors.

**Comment by larsoner** [comment]
Yes having `colors` as a limitation seems silly. I would add a `colors=None` argument that by default does what is done now, and allow `ndarray, shape ([n_seeds, ][3])` that allows setting the color of the labels manually. The `n_seeds` and `3` are both optional because it should be any array that broadcasts to shape `(n_seeds, 3)` so for example you can use `colors=0.` to get all black labels.

**Comment by olafhauk** [comment]
@larsoner I've just pushed #8519. Please let me know if that's what you had in mind.
