### ISSUE TITLE
Got some problem in raw.plot function 

### ISSUE THREAD

**Issue by LF9076** [mne-tools/mne-python#8694]
I have some files in mat format, I converted them to RawArray format, and set the correct ch_type and ch_names. But when the raw.plot function is called, the data is not displayed correctly, instead it becomes the following, it is me Is there something wrong with the code?

the code:
sampling_freq = 500  
ch_names = ['O2','O1','Oz','Pz','P4','CP4','P8','C4','TP8','T8',
                'P7','P3','CP3','CPz','Cz','FC4','FT8','TP7','C3','FCz',
                'Fz','F4','F8','T7','FT7','FC3','F3','Fp2','F7','Fp1']
ch_types = ['eeg']*30 
info = mne.create_info(ch_names=ch_names,ch_types=ch_types,sfreq=sampling_freq)
raw = mne.io.RawArray(data, info)
montage = mne.channels.make_standard_montage(kind = 'standard_1005', head_size=0.095)
raw.set_montage(montage)
raw.plot(events=event,duration=5,proj = False)

![1](https://user-images.githubusercontent.com/27933069/103474411-8e469180-4dde-11eb-91d4-70121e983df9.png)
![image](https://user-images.githubusercontent.com/27933069/103474444-d2d22d00-4dde-11eb-9e49-cec319acefe1.png)

****

**Comment by cbrnr** [comment]
Probably something wrong with `data`, maybe the scaling? MNE expects data to be in Volts and not µV, so typical values are something like `1e-6`. Can you show some values (e.g. `data[:2, :5]`)?

**Comment by msseibel** [comment]
Here, the obvious solution is to rescale the data array by something like `raw._data*=1e-6`.

I have a similar question but with MEG data. I dont wanted to scale the data directly, since I fear imprescision losses when scaling the data multiple times.
So I wanted to make use of the keys: `range`, `cal` and `unit_mul` . Therefore different scalings for `raw.info['chs'][i]['unit_mul'] `  were tested in the range 12, ... ,-12. But it has no affect on plotting. (On which functions does it have an effect?)

According to the Elekta Neuromag Functional Image File Format Documentation from March 2011, the relation between these three properties is: 
`raw._data*range*cal` and the unit of the result is defined by `unit` and `unit_mul`.  If `unit` is 112 (FIFF_UNIT_T) and `unit_mul` is -15 it means that data is provided in fT? And if `unit_mul` is 1 data should be interpreted as T?
What am I missing here?

So how can the setting of these properties be tested. I thought plotting would be the easiest way, or does the `scalings` in parameter `plot`  overwrites any effect of the three keys?

**Comment by larsoner** [comment]
@msseibel most of the entries in `info` (except `'bads'`) are really meant to be read-only. Changing `info['chs'][...]` in particular is likely to cause problems down the line because we assume that MNE code is the only place that these get changed.

> I dont wanted to scale the data directly, since I fear imprescision losses when scaling the data multiple times.

In your case I would just scale with `raw.apply_function(lambda x: x * 1e-6)` or so. I wouldn't worry too much about losing precision from this -- do you think you will need to do this many times with many values during many save-load round-trips?

> Here, the obvious solution is to rescale the data array by something like raw._data*=1e-6.

Doing `raw._data*=1e-6.` is not a good idea because `_data` is a private attribute, and we could remove it or change it at any time without warning between releases so your code could break.

**Comment by msseibel** [comment]
But when scaling the data directly is the correct way, what is then the meaning of the `unit_m`? 
Shouldn't `unit_m` also change when data is multiplied by a factor that represents a unit conversion?
E.g. when `x*=1e-3` then `unit_m` should be decreased by 3?

**Comment by msseibel** [comment]
My actual problem is not directly related to the OPs problem, but I was unaware of how `mne` understands units and there scale when it comes to methods that are connected to the physical world e.g. `maxwell_filter` .  Now I see that it is actually explained in the notes of `mne.io.RawArray`. 
Thank you for your time.
