### ISSUE TITLE
MNE Raw object Plot show disconnected signal points

### ISSUE THREAD

**Issue by abhincho** [mne-tools/mne-python#9717]
Hi

I am trying to read the files from the [STEW](https://ieee-dataport.org/open-access/stew-simultaneous-task-eeg-workload-dataset) dataset. The files are in .txt format. I create a info object and read the data into a numpy array and then converted it into a mne raw data object. I used the following code for doing that
`channel_names = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']`
`channel_type = ['eeg']*14`
`sampling_rate = 128`
`info = mne.create_info(ch_names=channel_names, sfreq=sampling_rate, ch_types=channel_type, verbose= True)`
`info.set_montage('standard_1020')`
`data = np.loadtxt("sub01_hi.txt", dtype=float)`
`raw = mne.io.RawArray(data.T, info)`

Now when I plot the raw object data, the plot shows straight vertical lines across channels but are disconnected for a single channel. 
But when I did the same thing  in Brainstorm i.e read the file in brainstorm and converted the raw file into edf format and read the edf file in mne using `mne.io.read_raw_edf,` I am getting a proper EEG signal plot

Please help.

**Comment by drammock** [comment]
The first thing to check is whether the units are correct. MNE-Python expects volts, your data may be in microvolts. Try multiplying by 1e-6 before creating the raw object.

By the way, questions like this are better suited for our online forum (mne.discourse.group); we try to reserve the GitHub issues for bugs/feature requests rather than user support.

**Comment by abhincho** [comment]
Thank you @drammock  and I will keep that in mind from next time.
Sorry for the inconvenience caused.
