### ISSUE TITLE
Failed to import dat files. 

### ISSUE THREAD

**Issue by sam1o1** [mne-tools/mne-python#9790]
#### Describe the bug
I was working on EEG data that was stored as dat files from the neurosky sensor. When I tried to import the data using `mne.channels.read_dig_dat` I got an error.

**Comment by sappelhoff** [comment]
`mne.channels.read_dig_dat` is a function to read electrode locations from some "Compumedics" file format, see:

https://github.com/mne-tools/mne-python/blob/2f6d6b4667af1a3214e1a84ae21f8109429770a3/mne/channels/montage.py#L463-L471

If you want to read EEG data, please have a look at this documentation page: https://mne.tools/dev/auto_tutorials/io/20_reading_eeg_data.html it lists all currently supported file formats. If the format you want to read is not yet supported, it'd be helpful if you could supply as much information (including links) as possible, so that people can get an impression of how easy/difficult/useful it'd be to implement reading support for your data format.

**Comment by sam1o1** [comment]
I tried to use mne.io.read_raw_persyst  and It failed too to load .dat files.

**Comment by sappelhoff** [comment]
I recommend you do some research into what data format your system (you mentioned "neurosky sensor") produces, and then help us with lots of info on that. :-)
